services:
  php-apache2:
    build:
      args:
        user: roni
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: auth-php-apache2
    container_name: auth-php-apache2
    ports:
      - 80:80 
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - auth

  mysql:
    image: mysql:8
    container_name: auth-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - auth

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: auth-phpmyadmin
    ports:
      - 8080:80
    restart: unless-stopped
    environment:
      PMA_HOST: mysql:3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - auth

networks:
  auth:
    driver: bridge